Add small_formatting argument to file_size
staticdev/human-readable pull request #692
Opened 2024-11-02 04:54 UTC by zwimer

Fixes: https://github.com/staticdev/human-readable/issues/691 by adding in a `small_formatting` argument which handles formatting when `value` is small enough that its suffix would be `B`, `Byte`, or `Bytes`.

2024-11-05 22:05 UTC, staticdev commented
@zwimer thanks for your contribution. Could you please add the necessary tests so i can approve it?

2024-11-05 22:07 UTC, staticdev requested changes

2024-11-05 22:07 UTC, staticdev commented on src/human_readable/files.py
> +    fmt = small_formatting if value < base else formatting
This linr is not covered by tests anymore.

2024-11-05 23:44 UTC, zwimer commented
I added test cases and noticed that among all the suffixes, there was one `kB` where everything else was capitalized it so I fixed that by changing it to `KB`.

2024-12-13 07:25 UTC, zwimer commented
@staticdev Is there anything else I can do to help get this merged?

2024-12-30 10:33 UTC, staticdev approved these changes

2024-12-30 10:33 UTC, merged

2024-12-30 10:33 UTC, staticdev commented
@zwimer merged, thanks.